server:
   port: 8097
  
#Conextion to Mongo DB
spring:
    application:     name: customerManagement    data:
         mongodb:           uri: mongodb://localhost:27017/customerManagement       
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8099/eureka/
#management:
 # endpoints:
 #   web:
 #     exposure:
 #       include: "*"