server:
   port: 8096
  
#Conextion to Mongo DB
spring:
    application:     name: customerManagement    data:
         mongodb:           uri: mongodb://localhost:27017/customerManagement       
