server:
   port: 8090
  
#Conextion to Mongo DB
spring:
  application:
    name: customer_service
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerManagement
         
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposre:
        include: "*"