server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
      - id: customer_service
        uri: http://localhost:8090/
        predicates:
        - Path=/customer/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
