server:
  port: 8092

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: customer-service
        uri: http://localhost:8099/
        predicates:
        - Path=/customer/**